default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: 3306
  password: password
  database: <%= ENV.fetch('DB_NAME', 'development_db') %>

test:
  <<: *default
  host: docker-db-service
  port: 3306
  password: password
  database: test_db

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>
