
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: "mysql2://pmk9cljb078n9i6h:hwqrz0ub6ggd2a62@d6rii63wp64rsfb5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/lxibsvy2fqsqgod5"
  username: "pmk9cljb078n9i6h"
  password: "hwqrz0ub6ggd2a622"
  url: "mysql2://pmk9cljb078n9i6h:hwqrz0ub6ggd2a62@d6rii63wp64rsfb5.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/lxibsvy2fqsqgod5"
