default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  host: 127.0.0.1
  port: 3307
  password: password
  database: teac_output_development

test:
  <<: *default
  host: docker-db-service
  port: 3306
  password: password
  database: teac_output_test

production:
  <<: *default
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '3306') %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV.fetch('DB_NAME', 'teac_output_production') %>
